services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: habit_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: ./habit-tracker-backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:Test123@db:5432/habit_tracker
      APP_NAME: Habit Tracker API
      APP_VERSION: 0.1.0
      DEBUG: "true"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
